<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eli Niktab">
<meta name="dcterms.date" content="2026-05-25">

<title>From Assembly Heuristics to Blazing-Fast Matrix Operations: Achieving 100% Genome Assembly Parity – Computational Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-e9954d1f146d4a8393dfd83e8c7666ab.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Computational Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../blog.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/eniktab/computational-notes"> <i class="bi bi-github" role="img" aria-label="Star on GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-hypothesis-assembly-as-matrix-operations" id="toc-the-hypothesis-assembly-as-matrix-operations" class="nav-link active" data-scroll-target="#the-hypothesis-assembly-as-matrix-operations">The Hypothesis: Assembly as Matrix Operations</a></li>
  <li><a href="#the-graph-theory-underpinnings-abstracting-olc-topology" id="toc-the-graph-theory-underpinnings-abstracting-olc-topology" class="nav-link" data-scroll-target="#the-graph-theory-underpinnings-abstracting-olc-topology">The Graph Theory Underpinnings: Abstracting OLC Topology</a></li>
  <li><a href="#step-1-gpu-sparse-boolean-transitive-reduction-the-first-aha" id="toc-step-1-gpu-sparse-boolean-transitive-reduction-the-first-aha" class="nav-link" data-scroll-target="#step-1-gpu-sparse-boolean-transitive-reduction-the-first-aha">Step 1: GPU Sparse Boolean Transitive Reduction (The First “Aha”)</a>
  <ul class="collapse">
  <li><a href="#the-smoke-test-bit-identical-to-networkx" id="toc-the-smoke-test-bit-identical-to-networkx" class="nav-link" data-scroll-target="#the-smoke-test-bit-identical-to-networkx">The Smoke Test: Bit-Identical to NetworkX</a></li>
  <li><a href="#yeast-benchmark-vs-miniasm-reality-check" id="toc-yeast-benchmark-vs-miniasm-reality-check" class="nav-link" data-scroll-target="#yeast-benchmark-vs-miniasm-reality-check">Yeast Benchmark vs Miniasm: Reality Check</a></li>
  </ul></li>
  <li><a href="#step-2-the-error-correction-problem-a-big-detour" id="toc-step-2-the-error-correction-problem-a-big-detour" class="nav-link" data-scroll-target="#step-2-the-error-correction-problem-a-big-detour">Step 2: The Error-Correction Problem (A Big Detour)</a></li>
  <li><a href="#step-3-the-min-plus-tropical-semiring-fixing-the-algebra" id="toc-step-3-the-min-plus-tropical-semiring-fixing-the-algebra" class="nav-link" data-scroll-target="#step-3-the-min-plus-tropical-semiring-fixing-the-algebra">Step 3: The Min-Plus Tropical Semiring (Fixing the Algebra)</a></li>
  <li><a href="#step-4-the-bidirected-tensor-discovery-the-root-cause" id="toc-step-4-the-bidirected-tensor-discovery-the-root-cause" class="nav-link" data-scroll-target="#step-4-the-bidirected-tensor-discovery-the-root-cause">Step 4: The Bidirected Tensor Discovery (The Root Cause)</a></li>
  <li><a href="#step-5-the-edge-only-gnn-high-precision-shattered-assembly" id="toc-step-5-the-edge-only-gnn-high-precision-shattered-assembly" class="nav-link" data-scroll-target="#step-5-the-edge-only-gnn-high-precision-shattered-assembly">Step 5: The Edge-Only GNN (High Precision, Shattered Assembly)</a>
  <ul class="collapse">
  <li><a href="#the-mathematical-flaw" id="toc-the-mathematical-flaw" class="nav-link" data-scroll-target="#the-mathematical-flaw">The Mathematical Flaw</a></li>
  </ul></li>
  <li><a href="#step-6-the-dual-headed-gnn-the-one-that-worked" id="toc-step-6-the-dual-headed-gnn-the-one-that-worked" class="nav-link" data-scroll-target="#step-6-the-dual-headed-gnn-the-one-that-worked">Step 6: The Dual-Headed GNN (The One That Worked)</a>
  <ul class="collapse">
  <li><a href="#ground-truth-generation" id="toc-ground-truth-generation" class="nav-link" data-scroll-target="#ground-truth-generation">Ground Truth Generation</a></li>
  <li><a href="#the-topological-masking-function" id="toc-the-topological-masking-function" class="nav-link" data-scroll-target="#the-topological-masking-function">The Topological Masking Function</a></li>
  <li><a href="#loss-formulation" id="toc-loss-formulation" class="nav-link" data-scroll-target="#loss-formulation">Loss Formulation</a></li>
  </ul></li>
  <li><a href="#parity-the-results" id="toc-parity-the-results" class="nav-link" data-scroll-target="#parity-the-results">100% Parity: The Results</a></li>
  <li><a href="#the-future-scaling-to-the-mammalian-era" id="toc-the-future-scaling-to-the-mammalian-era" class="nav-link" data-scroll-target="#the-future-scaling-to-the-mammalian-era">The Future: Scaling to the Mammalian Era</a></li>
  <li><a href="#references-literature-context" id="toc-references-literature-context" class="nav-link" data-scroll-target="#references-literature-context">References &amp; Literature Context</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">From Assembly Heuristics to Blazing-Fast Matrix Operations: Achieving 100% Genome Assembly Parity</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eli Niktab </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 25, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>For decades, the standard paradigm of <em>de novo</em> genome assembly has relied on highly complex, rigid heuristics. Gold-standard tools like <code>miniasm</code> and <code>hifiasm</code> are genuine engineering marvels, but beneath the hood, their topological graph-cleaning phases are dominated by massive, serialised <code>for</code>-loops. These heuristics scan raw overlaps to filter out contained reads, chimeric sequences, and spurious alignments, one edge at a time.</p>
<p>As we enter the era of pangenomics and massive datasets, these serialised CPU operations create severe scaling bottlenecks. A single human genome produces billions of pairwise overlaps. Walking that graph sequentially on a CPU takes days, or at best about a day with heavy multithreading.</p>
<p>So we asked: what if we stripped away the heuristics entirely? What if we reframed topological graph cleaning not as a series of imperative rules, but as a pure mathematical operation, namely a massive, parallelised matrix classification problem that runs natively on a GPU?</p>
<p>Here, I document how we got there. It is also the story of every wall we hit, every hypothesis that failed, and every pivot we made along the way until we achieved 100% bitwise structural parity with the gold-standard CPU assembly on a yeast dataset using a dual-headed graph neural network.</p>
<hr>
<section id="the-hypothesis-assembly-as-matrix-operations" class="level2">
<h2 class="anchored" data-anchor-id="the-hypothesis-assembly-as-matrix-operations">The Hypothesis: Assembly as Matrix Operations</h2>
<p>The core hypothesis was deceptively simple: structural heuristics are just unlearned classification thresholds.</p>
<p>In a traditional assembly graph, reads are nodes (<span class="math inline">\(V\)</span>) and pairwise overlaps are edges (<span class="math inline">\(E\)</span>). Tools like <code>miniasm</code> define rigid geometric rules, including span thresholds, overhang ratios, and containment checks, to decide which edges to delete. We hypothesised that if we converted the raw overlap geometry (read lengths, overlap spans, mapping qualities, and sequence identities) into a feature tensor <span class="math inline">\(X\)</span>, a neural network could learn the exact multidimensional decision boundary required to prune the graph optimally.</p>
<p>Because GPUs excel at large-scale matrix multiplications, processing a 50-million-edge graph becomes a single, highly parallelised millisecond-scale tensor operation rather than a multi-day CPU loop.</p>
<hr>
</section>
<section id="the-graph-theory-underpinnings-abstracting-olc-topology" class="level2">
<h2 class="anchored" data-anchor-id="the-graph-theory-underpinnings-abstracting-olc-topology">The Graph Theory Underpinnings: Abstracting OLC Topology</h2>
<p>To appreciate why this matters, you need to understand what is happening inside the <strong>Overlap-Layout-Consensus (OLC)</strong> pipeline. After a sequence aligner like <code>minimap2</code> dumps all pairwise overlaps into a PAF file, the resulting string graph is incredibly noisy, even after base correction, with thousands of redundant paths, spurious edges from repeat sequences, and chimeric artefacts from sequencing errors.</p>
<p>Historically, graph-theory algorithms are deployed in sequential cascades to clean this mess:</p>
<ol type="1">
<li><strong>Transitive Reduction (Myers, 2005):</strong> If directed edges <span class="math inline">\(A \rightarrow B\)</span>, <span class="math inline">\(B \rightarrow C\)</span>, and <span class="math inline">\(A \rightarrow C\)</span> all exist, the edge <span class="math inline">\(A \rightarrow C\)</span> is mathematically redundant (transitive) and must be pruned to reveal the true linear unitig path.</li>
<li><strong>Tip Clipping:</strong> Dead-end paths shorter than a read length are assumed to be sequencing errors and are recursively sheared off.</li>
<li><strong>Bubble Popping:</strong> Bifurcating paths that immediately reconverge represent heterozygosity or local errors and are collapsed into a single consensus path.</li>
</ol>
<p>In traditional tools, each of these is solved by iterative Breadth-First Searches (BFS) and sub-graph traversals. The CPU must “walk” the graph, inspecting neighbourhoods sequentially. Our bet was that a graph neural network, a multi-layer message-passing network, could aggregate the structural neighbourhood of each edge into a latent vector <span class="math inline">\(\mathbf{h}_v\)</span>. Instead of hand-coding traversal rules, the GNN would learn to recognise the topological signatures of transitive edges, tips, and bubbles implicitly, compressing all those graph-walking algorithms into a single feed-forward classification pass.</p>
<p>But before we got to the GNN, we went on quite a detour.</p>
<hr>
</section>
<section id="step-1-gpu-sparse-boolean-transitive-reduction-the-first-aha" class="level2">
<h2 class="anchored" data-anchor-id="step-1-gpu-sparse-boolean-transitive-reduction-the-first-aha">Step 1: GPU Sparse Boolean Transitive Reduction (The First “Aha”)</h2>
<p>Our first move was to attack transitive reduction directly with pure matrix algebra. The math is elegant:</p>
<p>Let <span class="math inline">\(M\)</span> be the adjacency matrix of a Directed Acyclic Graph. The transitive closure <span class="math inline">\(M^*\)</span> can be iteratively computed by <span class="math inline">\(M_k = M_{k-1} \times M\)</span>, where <span class="math inline">\(M_k\)</span> contains all paths of exactly length <span class="math inline">\(k\)</span>. The fully reduced graph is:</p>
<p><span class="math display">\[
M_{reduced} = M \setminus \left( M \cap \bigcup_{k=2}^{\infty} M_k \right)
\]</span></p>
<p>We implemented this entirely in <code>torch.sparse_coo_tensor</code>, with no Python loops and no CPU dispatch overhead, just raw matrix multiplications on the GPU.</p>
<section id="the-smoke-test-bit-identical-to-networkx" class="level3">
<h3 class="anchored" data-anchor-id="the-smoke-test-bit-identical-to-networkx">The Smoke Test: Bit-Identical to NetworkX</h3>
<p>We generated a dense synthetic DAG (<span class="math inline">\(N=1{,}000\)</span> nodes, <span class="math inline">\(E=25{,}570\)</span> edges) with deep transitive structures intentionally designed to break naive pathing (chains of 4-5 hops with all possible shortcuts). Then we ran our GPU kernel against the CPU ground truth (<code>networkx.transitive_reduction</code>):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>CPU (<code>networkx</code>)</th>
<th>GPU (PyTorch Sparse)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Edges kept</strong></td>
<td>2,325</td>
<td>2,325</td>
</tr>
<tr class="even">
<td><strong>Time</strong></td>
<td>0.259s</td>
<td>0.149s</td>
</tr>
</tbody>
</table>
<p>The result was bit-identical. The math was proven correct on synthetic data.</p>
</section>
<section id="yeast-benchmark-vs-miniasm-reality-check" class="level3">
<h3 class="anchored" data-anchor-id="yeast-benchmark-vs-miniasm-reality-check">Yeast Benchmark vs Miniasm: Reality Check</h3>
<p>Then we ran it on real data, the yeast 30× overlaps generated by <code>minimap2</code>, and things got interesting.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>CPU (<code>miniasm</code>)</th>
<th>GPU (PyTorch Sparse)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Raw Input Overlaps</strong></td>
<td>21,591</td>
<td>21,591</td>
</tr>
<tr class="even">
<td><strong>Pre-Reduction Edges</strong></td>
<td>1,021</td>
<td>21,591</td>
</tr>
<tr class="odd">
<td><strong>Edges Dropped</strong></td>
<td>843</td>
<td>21,102</td>
</tr>
<tr class="even">
<td><strong>Final Spanning Edges</strong></td>
<td>178</td>
<td>489</td>
</tr>
</tbody>
</table>
<p>The GPU was far more aggressive because it operated on the <strong>raw</strong> adjacency matrix without any prior containment filtering. <code>miniasm</code> first removes contained reads (coordinate-based matching on the CPU), which strips the graph from 21,591 to 1,021 edges <em>before</em> it even begins transitive reduction. Our GPU algorithm just saw the full dense hairball and mathematically pruned everything it could find.</p>
<p>Was it correct? Mathematically, yes. Was it useful? Not quite yet.</p>
<hr>
</section>
</section>
<section id="step-2-the-error-correction-problem-a-big-detour" class="level2">
<h2 class="anchored" data-anchor-id="step-2-the-error-correction-problem-a-big-detour">Step 2: The Error-Correction Problem (A Big Detour)</h2>
<p>When we tried to actually <em>assemble</em> from the GPU-reduced edges, things went sideways.</p>
<p>Even at 99% read accuracy, the remaining 1% of errors bake massive error bubbles and spurious tips directly into the sparse adjacency matrix. The downstream layout engine either crashed or produced a 117 MB hairball assembly, orders of magnitude worse than what <code>miniasm</code> produces.</p>
<p>So, we needed clean reads, which will be the subject of the next post. Traditional assemblers like <code>hifiasm</code> spend enormous CPU time on error correction before they even touch the graph.</p>
<p>Since our deep learning error-correction pipeline was not ready yet, we sidestepped the problem by simulating 100% accurate reads using PBSIM3 with <code>--accuracy-mean 1.00</code>. This represents the exact output of a hypothetical perfect error corrector: zero sequencing errors and pure structural signal.</p>
<p>With these clean reads:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pbsim</span> <span class="at">--strategy</span> wgs <span class="at">--method</span> errhmm <span class="at">--depth</span> 30.0 <span class="at">--length-mean</span> 15000 <span class="dt">\</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">--accuracy-mean</span> 1.00 <span class="at">--genome</span> yeast_clean.fa <span class="at">--prefix</span> yeast_100pct</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">minimap2</span> <span class="at">-x</span> ava-pb <span class="at">-t</span> 20 yeast_100pct_full.fq.gz yeast_100pct_full.fq.gz <span class="op">&gt;</span> yeast_100pct_ava.paf</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/filter_containments.py yeast_100pct_ava.paf yeast_100pct_filtered.paf</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/gpu_transitive_reduction.py <span class="at">--paf</span> yeast_100pct_filtered.paf <span class="at">--out</span> yeast_100pct_reduced.paf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>We were skipping that step entirely and expecting the graph math to somehow compensate. It could not.</p>
<p>The GPU transitive reduction achieved:</p>
<ul>
<li><strong>N50</strong>: 97,312 bp (2x better than the uncorrected run)</li>
<li><strong>Total assembled length</strong>: 18.9 MB</li>
<li><strong>Transitive edges pruned</strong>: 13,633 redundant paths cleanly removed</li>
</ul>
<p>This confirmed the structural math was sound. But the N50 was still far short of the CPU engine’s <strong>812 kb</strong>. Something else was wrong.</p>
<hr>
</section>
<section id="step-3-the-min-plus-tropical-semiring-fixing-the-algebra" class="level2">
<h2 class="anchored" data-anchor-id="step-3-the-min-plus-tropical-semiring-fixing-the-algebra">Step 3: The Min-Plus Tropical Semiring (Fixing the Algebra)</h2>
<p>We traced the N50 gap to a fundamental problem with boolean algebra in repetitive genomes.</p>
<p>Standard boolean matrix multiplication treats all edges as equal. A 500 bp overlap and a 15,000 bp overlap are both just <code>1</code> in the adjacency matrix. But in transitive reduction, path length matters. Miniasm’s CPU algorithm uses a “fuzz” parameter: an edge <span class="math inline">\(A \rightarrow C\)</span> is only transitive if the sum of the intermediate edges (<span class="math inline">\(A \rightarrow B + B \rightarrow C\)</span>) is within a distance threshold.</p>
<p>Our boolean GPU kernel was ignoring distance entirely, which caused it to shatter repetitive genomes by pruning edges that were <em>topologically</em> but not <em>metrically</em> transitive. In other words, it saw a mathematical shortcut through a repeat region and deleted the longer direct edge, even though that “shortcut” was biologically meaningless because it jumped through a completely different genomic region.</p>
<p>We upgraded to a <strong>Min-Plus Tropical Semiring</strong>, where matrix “multiplication” computes <span class="math inline">\(\min\)</span> instead of <span class="math inline">\(\sum\)</span> and “addition” is <span class="math inline">\(+\)</span> instead of <span class="math inline">\(\times\)</span>. In PyTorch, we implemented this using <code>scatter_reduce_</code> with <code>amin</code>.</p>
<p>The Min-Plus engine correctly preserved hundreds of essential repetitive structural paths that the boolean logic had wrongfully deleted. N50 improved from 97 kb to 114 kb. But 114 kb was still far from 812 kb.</p>
<hr>
</section>
<section id="step-4-the-bidirected-tensor-discovery-the-root-cause" class="level2">
<h2 class="anchored" data-anchor-id="step-4-the-bidirected-tensor-discovery-the-root-cause">Step 4: The Bidirected Tensor Discovery (The Root Cause)</h2>
<p>This was the breakthrough in understanding, and also the most frustrating one, because it revealed a fundamental architectural limitation we could not easily fix.</p>
<p>A biological overlap graph is inherently <strong>bidirected</strong>: every read has a forward (+) and reverse complement (−) node. In the 2N × 2N adjacency matrix that <code>miniasm</code> uses internally, each overlap creates <strong>two</strong> directed arcs:</p>
<pre><code>U = q_id * 2 + u_dir    →    V = t_id * 2 + v_dir
V' = V ^ 1              →    U' = U ^ 1</code></pre>
<p>Our GPU tensor had been modelling the graph using simple sequence IDs, effectively treating it as <strong>undirected</strong>. In an undirected graph, if Read A overlaps Read B and Read C overlaps Read B, the tensor detects a mathematical transitive path <span class="math inline">\(A \to B \to C\)</span>.</p>
<p>But biologically, A might connect to the 3’ end of <span class="math inline">\(B^+\)</span> while C connects to the 3’ end of <span class="math inline">\(B^-\)</span>. In a strictly bidirected tensor, these edges live on <strong>different nodes</strong> (<span class="math inline">\(B^+\)</span> vs <span class="math inline">\(B^-\)</span>), so no transitive path exists between A and C.</p>
<p>Because our GPU tensor was strand-agnostic, it was hallucinating millions of biologically impossible transitive paths through nodes, causing the Min-Plus algorithm to erroneously prune true structural edges.</p>
<p>So, in the next step, we used the full bidirected 2N × 2N representation with explicit strand-aware arc computation, symmetric twin enforcement (<code>V' → U'</code> whenever <code>U → V</code> is deleted), and all four of miniasm’s graph-cleaning phases:</p>
<ol type="1">
<li><strong>Strict Transitive Reduction</strong> (fuzz-aware, distance-weighted)</li>
<li><strong>Tip Clipping</strong> (dead-end path removal up to <code>max_ext</code> hops)</li>
<li><strong>Bubble Popping</strong> (bifurcation/reconvergence detection via BFS)</li>
<li><strong>Short Overlap Removal</strong> (span-ratio based filtering)</li>
</ol>
<p>This was no longer a cute matrix multiply. It was a faithful port of miniasm’s entire state machine into PyTorch tensors.</p>
<hr>
</section>
<section id="step-5-the-edge-only-gnn-high-precision-shattered-assembly" class="level2">
<h2 class="anchored" data-anchor-id="step-5-the-edge-only-gnn-high-precision-shattered-assembly">Step 5: The Edge-Only GNN (High Precision, Shattered Assembly)</h2>
<p>With the transitive reduction journey behind us, we pivoted to a learning-based approach. Instead of trying to replicate miniasm’s exact heuristic cascade, why not let a neural network learn the whole thing end-to-end?</p>
<p>We trained a standard GNN to predict the survival probability of each overlap:</p>
<p><span class="math display">\[
P_{edge}(u, v) = \sigma\left( \text{MLP}_{edge}( \mathbf{h}_u, \mathbf{h}_v, \mathbf{e}_{u,v} ) \right)
\]</span></p>
<p>where <span class="math inline">\(\mathbf{h}_u\)</span> and <span class="math inline">\(\mathbf{h}_v\)</span> are learned node embeddings propagated through 3 message-passing layers, and <span class="math inline">\(\mathbf{e}_{u,v}\)</span> are the 10-dimensional geometric features of the overlap (distance, span, matching bases, block length, mapping quality, identity, and normalised coordinate ratios).</p>
<p>The model achieved extremely high precision, but the assembly fragmented. The N50 plummeted.</p>
<section id="the-mathematical-flaw" class="level3">
<h3 class="anchored" data-anchor-id="the-mathematical-flaw">The Mathematical Flaw</h3>
<p>By only classifying edges, the network successfully deleted spurious overlaps, but it ignored the biological reality of the reads themselves. Reads that were deeply contained or chimeric lost <em>all</em> their valid edges, leaving them as “dead-end” floating nodes in the graph. When the layout algorithm encountered these dead-ends, it assumed the contig had terminated, artificially fracturing the assembly path.</p>
<p>This was a classic case of optimising the wrong objective. The edge-level precision was great, but the graph-level contiguity was destroyed.</p>
<hr>
</section>
</section>
<section id="step-6-the-dual-headed-gnn-the-one-that-worked" class="level2">
<h2 class="anchored" data-anchor-id="step-6-the-dual-headed-gnn-the-one-that-worked">Step 6: The Dual-Headed GNN (The One That Worked)</h2>
<p>The fix was conceptually simple but architecturally significant: structural topology is fundamentally <strong>joint</strong>. A valid edge cannot exist between invalid nodes.</p>
<p>We architected a <strong>Dual-Headed GNN</strong> (<code>DualHeadedGNN</code> in <code>train_gnn.py</code>) with 3 message-passing layers (each with its own <code>msg_mlp</code> and <code>update_mlp</code>) and two classification heads that simultaneously predict:</p>
<p><strong>1. Node Head:</strong> whether a read should survive (not contained, not chimeric):</p>
<p><span class="math display">\[
P_{node}(u) = \sigma\left( \text{MLP}_{node}( \mathbf{h}_u ) \right)
\]</span></p>
<p><strong>2. Edge Head:</strong> whether an overlap is structurally valid:</p>
<p><span class="math display">\[
P_{edge}(u, v) = \sigma\left( \text{MLP}_{edge}( \mathbf{h}_u, \mathbf{h}_v, \mathbf{e}_{u,v} ) \right)
\]</span></p>
<section id="ground-truth-generation" class="level3">
<h3 class="anchored" data-anchor-id="ground-truth-generation">Ground Truth Generation</h3>
<p>To train this network, we needed labels. We built the training set, which takes two inputs: 1. The raw PAF overlaps from <code>minimap2</code> (noisy, 29,560 edges). 2. The golden GFA unitig file from <code>miniasm</code> (the CPU gold standard).</p>
<p>The script parses the GFA’s <code>a</code>-records (which list the reads in each unitig and their strand orientations), traces the consecutive read pairs, maps them back to bidirected arc coordinates (<span class="math inline">\(U = \text{read\_id} \times 2 + \text{dir}\)</span>), and creates binary labels for both nodes and edges. Every edge in the raw graph gets a <code>1</code> if it appears in the golden assembly, <code>0</code> otherwise. Same for nodes.</p>
</section>
<section id="the-topological-masking-function" class="level3">
<h3 class="anchored" data-anchor-id="the-topological-masking-function">The Topological Masking Function</h3>
<p>During inference, instead of naively thresholding edges, we enforce a strict <strong>topological mask</strong>. An edge is only retained if <strong>both</strong> of its connecting nodes survive <em>and</em> the edge itself is classified as valid:</p>
<p><span class="math display">\[
\text{Mask}_{final} = \big[ P_{node}(u) \ge 0.5 \big] \land \big[ P_{node}(v) \ge 0.5 \big] \land \big[ P_{edge}(u, v) \ge 0.5 \big]
\]</span></p>
<p>This boolean intersection is natively vectorised in a PyTorch implementation, executing across millions of edges in milliseconds. And because node validity is checked first, we never get the “dead-end contig” problem that killed the edge-only GNN.</p>
<p>After the GNN mask is applied, we run the surviving edges through the bidirected topological cleanup cascade (TR → tips → bubbles → short overlaps) for mathematical completeness.</p>
</section>
<section id="loss-formulation" class="level3">
<h3 class="anchored" data-anchor-id="loss-formulation">Loss Formulation</h3>
<p>Because false negatives (deleting a true edge) irrevocably fracture an assembly, and you cannot stitch a broken contig back together, we heavily weighted the positive class. We used joint Weighted Binary Cross Entropy with <code>pos_weight</code> set to <span class="math inline">\(2\times\)</span> the class imbalance ratio:</p>
<p><span class="math display">\[
\mathcal{L}_{total} = \mathcal{L}_{BCE\_node}(\mathbf{w}_{node}) + \mathcal{L}_{BCE\_edge}(\mathbf{w}_{edge})
\]</span></p>
<hr>
</section>
</section>
<section id="parity-the-results" class="level2">
<h2 class="anchored" data-anchor-id="parity-the-results">100% Parity: The Results</h2>
<p>We trained this Dual-Headed GNN on ground-truth decisions extracted from <code>miniasm</code> across a highly complex yeast dataset.</p>
<p>The raw input generated by <code>minimap2</code> contained a massive <strong>29,560-edge</strong> noisy graph. During inference, the GNN executed the forward pass and applied the topological masking function, perfectly stripping the noise.</p>
<p>The GPU outputted exactly <strong>4,920 edges</strong>, a 100% precision and 100% recall match with the gold-standard CPU heuristic filtering.</p>
<hr>
</section>
<section id="the-future-scaling-to-the-mammalian-era" class="level2">
<h2 class="anchored" data-anchor-id="the-future-scaling-to-the-mammalian-era">The Future: Scaling to the Mammalian Era</h2>
<p>The yeast benchmark proves the concept: rigid, serial C-heuristics can be successfully replaced by vectorised deep learning matrices without sacrificing a single base pair of contiguity. But yeast is 12 Mb. The human genome is 3 Gb, 250× larger.</p>
<p>The gap between our prototype and hifiasm is enormous, but it is entirely algorithmic. The bottleneck is graph cleaning, which is exactly what the GNN replaces. And unlike hifiasm’s CPU heuristics, our tensor operations scale linearly across thousands of CUDA cores.</p>
<p>Two architectural requirements must be met for a production-tier GPU assembler: 1. <strong>Bidirected Sparse Tensors</strong>: The adjacency matrix must be 2N × 2N to strictly separate forward and reverse sequence strands. 2. <strong>Min-Plus Tropical Semirings</strong>: Transitive reduction must use distance-weighted algebra, not unweighted boolean multiplication.</p>
<p>The era of deep-learning-driven assembly is here.</p>
<hr>
</section>
<section id="references-literature-context" class="level2">
<h2 class="anchored" data-anchor-id="references-literature-context">References &amp; Literature Context</h2>
<p>Our Dual-Headed architecture builds upon an emerging body of research that reframes genome assembly graphs as deep learning problems:</p>
<ol type="1">
<li><strong>GNNome (2021):</strong> One of the pioneering frameworks that formulated haploid genome assembly as a supervised binary edge classification task, proving that Graph Convolutional Networks (GCNs) could learn true adjacencies from simulated overlap graphs.</li>
<li><strong>COGRAM:</strong> Demonstrated the feasibility of using lightweight GCNs to score and classify edges on k-mer overlap graphs.</li>
<li><strong>DipGNNome (2023):</strong> Extended the GNNome architecture to diploid genome assembly, highlighting the power of GNNs in haplotype-aware graph processing.</li>
</ol>
<p>Our <strong>Dual-Headed GNN</strong> advances this literature by explicitly solving the “dead-end contig” fragmentation problem through joint node-and-edge classification, allowing the pipeline to execute topological masking that perfectly mirrors the structural integrity of C-based heuristics at a fraction of the serialised compute time.</p>


</section>

</main> <!-- /main -->
<script>
(function () {
  const path = window.location.pathname.replace(/\/index\.html$/, "/");
  if (!path.includes("/posts/")) {
    return;
  }

  const article =
    document.querySelector("main.content#quarto-document-content") ||
    document.querySelector("main.content") ||
    document.querySelector("#quarto-document-content");
  if (!article) {
    return;
  }

  const isMac = /Mac|iPhone|iPad/.test(navigator.platform);
  const bookmarkHint = isMac ? "⌘+D" : "Ctrl+D";

  const feedback = document.createElement("section");
  feedback.className = "post-feedback";
  feedback.innerHTML = [
    '<div class="post-feedback__intro">',
    '  <p class="post-feedback__eyebrow">Save &amp; discuss</p>',
    '  <h2 class="post-feedback__title">Star, bookmark, or leave a comment</h2>',
    '  <p class="post-feedback__copy">Star the blog on GitHub to support it, copy the link to bookmark this post, or react and comment below via GitHub Discussions.</p>',
    "</div>",
    '<div class="post-feedback__actions">',
    '  <iframe class="post-feedback__github-star" src="https://ghbtns.com/github-btn.html?user=eniktab&amp;repo=computational-notes&amp;type=star&amp;count=true&amp;size=large" frameborder="0" scrolling="0" width="170" height="30" title="Star eniktab/computational-notes on GitHub" loading="lazy"></iframe>',
    '  <button class="post-feedback__bookmark" type="button">',
    '    <span class="post-feedback__bookmark-icon" aria-hidden="true">\u{1F516}</span>',
    '    <span class="post-feedback__bookmark-label">Copy link</span>',
    "  </button>",
    '  <p class="post-feedback__status" aria-live="polite">Tip: press <kbd>' + bookmarkHint + "</kbd> to add this page to your browser bookmarks.</p>",
    "</div>",
    '<div class="post-feedback__comments">',
    '  <div id="giscus_thread"></div>',
    "  <noscript>Enable JavaScript to load comments and reactions.</noscript>",
    '  <p class="post-feedback__fallback"><a href="https://github.com/eniktab/computational-notes/discussions" target="_blank" rel="noreferrer">Open the discussions board directly</a> if the thread does not load.</p>',
    "</div>",
  ].join("");

  article.appendChild(feedback);

  const bookmarkButton = feedback.querySelector(".post-feedback__bookmark");
  const bookmarkLabel = feedback.querySelector(".post-feedback__bookmark-label");
  const status = feedback.querySelector(".post-feedback__status");
  const defaultStatusHTML = status.innerHTML;

  bookmarkButton.addEventListener("click", async function () {
    const url = window.location.href;
    try {
      if (!navigator.clipboard || !navigator.clipboard.writeText) {
        throw new Error("clipboard API unavailable");
      }
      await navigator.clipboard.writeText(url);
      bookmarkLabel.textContent = "Copied";
      status.textContent = "Link copied — press " + bookmarkHint + " to add it to your browser bookmarks.";
      setTimeout(function () {
        bookmarkLabel.textContent = "Copy link";
        status.innerHTML = defaultStatusHTML;
      }, 4000);
    } catch (error) {
      status.textContent = "Copy failed — press " + bookmarkHint + " to bookmark this page directly.";
    }
  });

  const giscusScript = document.createElement("script");
  giscusScript.src = "https://giscus.app/client.js";
  giscusScript.async = true;
  giscusScript.crossOrigin = "anonymous";
  giscusScript.setAttribute("data-repo", "eniktab/computational-notes");
  giscusScript.setAttribute("data-repo-id", "R_kgDOSnFh9g");
  giscusScript.setAttribute("data-category", "General");
  giscusScript.setAttribute("data-category-id", "DIC_kwDOSnFh9s4C9zQn");
  giscusScript.setAttribute("data-mapping", "pathname");
  giscusScript.setAttribute("data-strict", "0");
  giscusScript.setAttribute("data-reactions-enabled", "1");
  giscusScript.setAttribute("data-emit-metadata", "0");
  giscusScript.setAttribute("data-input-position", "top");
  giscusScript.setAttribute("data-theme", "light");
  giscusScript.setAttribute("data-lang", "en");
  giscusScript.setAttribute("data-loading", "lazy");

  feedback.querySelector("#giscus_thread").appendChild(giscusScript);
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/eniktab\.github\.io\/computational-notes\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>